/*
PingAccess Administrative API

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess.

API version: 7.1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// SidebandClientCredentials The sideband client credentials.
type SidebandClientCredentials struct {
	// The created date of the credentials as the number of milliseconds since January 1, 1970, 00:00:00 GMT.
	Created *time.Time `json:"created,omitempty"`
	CredentialsType *SidebandClientCredentialsType `json:"credentialsType,omitempty"`
	SharedSecretConfig SidebandSharedSecretConfig `json:"sharedSecretConfig"`
}

// NewSidebandClientCredentials instantiates a new SidebandClientCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSidebandClientCredentials(sharedSecretConfig SidebandSharedSecretConfig) *SidebandClientCredentials {
	this := SidebandClientCredentials{}
	this.SharedSecretConfig = sharedSecretConfig
	return &this
}

// NewSidebandClientCredentialsWithDefaults instantiates a new SidebandClientCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSidebandClientCredentialsWithDefaults() *SidebandClientCredentials {
	this := SidebandClientCredentials{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *SidebandClientCredentials) GetCreated() time.Time {
	if o == nil || isNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SidebandClientCredentials) GetCreatedOk() (*time.Time, bool) {
	if o == nil || isNil(o.Created) {
    return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *SidebandClientCredentials) HasCreated() bool {
	if o != nil && !isNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *SidebandClientCredentials) SetCreated(v time.Time) {
	o.Created = &v
}

// GetCredentialsType returns the CredentialsType field value if set, zero value otherwise.
func (o *SidebandClientCredentials) GetCredentialsType() SidebandClientCredentialsType {
	if o == nil || isNil(o.CredentialsType) {
		var ret SidebandClientCredentialsType
		return ret
	}
	return *o.CredentialsType
}

// GetCredentialsTypeOk returns a tuple with the CredentialsType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SidebandClientCredentials) GetCredentialsTypeOk() (*SidebandClientCredentialsType, bool) {
	if o == nil || isNil(o.CredentialsType) {
    return nil, false
	}
	return o.CredentialsType, true
}

// HasCredentialsType returns a boolean if a field has been set.
func (o *SidebandClientCredentials) HasCredentialsType() bool {
	if o != nil && !isNil(o.CredentialsType) {
		return true
	}

	return false
}

// SetCredentialsType gets a reference to the given SidebandClientCredentialsType and assigns it to the CredentialsType field.
func (o *SidebandClientCredentials) SetCredentialsType(v SidebandClientCredentialsType) {
	o.CredentialsType = &v
}

// GetSharedSecretConfig returns the SharedSecretConfig field value
func (o *SidebandClientCredentials) GetSharedSecretConfig() SidebandSharedSecretConfig {
	if o == nil {
		var ret SidebandSharedSecretConfig
		return ret
	}

	return o.SharedSecretConfig
}

// GetSharedSecretConfigOk returns a tuple with the SharedSecretConfig field value
// and a boolean to check if the value has been set.
func (o *SidebandClientCredentials) GetSharedSecretConfigOk() (*SidebandSharedSecretConfig, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SharedSecretConfig, true
}

// SetSharedSecretConfig sets field value
func (o *SidebandClientCredentials) SetSharedSecretConfig(v SidebandSharedSecretConfig) {
	o.SharedSecretConfig = v
}

func (o SidebandClientCredentials) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !isNil(o.CredentialsType) {
		toSerialize["credentialsType"] = o.CredentialsType
	}
	if true {
		toSerialize["sharedSecretConfig"] = o.SharedSecretConfig
	}
	return json.Marshal(toSerialize)
}

type NullableSidebandClientCredentials struct {
	value *SidebandClientCredentials
	isSet bool
}

func (v NullableSidebandClientCredentials) Get() *SidebandClientCredentials {
	return v.value
}

func (v *NullableSidebandClientCredentials) Set(val *SidebandClientCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableSidebandClientCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableSidebandClientCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSidebandClientCredentials(val *SidebandClientCredentials) *NullableSidebandClientCredentials {
	return &NullableSidebandClientCredentials{value: val, isSet: true}
}

func (v NullableSidebandClientCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSidebandClientCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


