/*
PingAccess Administrative API

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess.

API version: 7.1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RequestPreservationTypes struct for RequestPreservationTypes
type RequestPreservationTypes struct {
	Items []Item `json:"items"`
}

// NewRequestPreservationTypes instantiates a new RequestPreservationTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestPreservationTypes(items []Item) *RequestPreservationTypes {
	this := RequestPreservationTypes{}
	this.Items = items
	return &this
}

// NewRequestPreservationTypesWithDefaults instantiates a new RequestPreservationTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestPreservationTypesWithDefaults() *RequestPreservationTypes {
	this := RequestPreservationTypes{}
	return &this
}

// GetItems returns the Items field value
func (o *RequestPreservationTypes) GetItems() []Item {
	if o == nil {
		var ret []Item
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *RequestPreservationTypes) GetItemsOk() ([]Item, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *RequestPreservationTypes) SetItems(v []Item) {
	o.Items = v
}

func (o RequestPreservationTypes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableRequestPreservationTypes struct {
	value *RequestPreservationTypes
	isSet bool
}

func (v NullableRequestPreservationTypes) Get() *RequestPreservationTypes {
	return v.value
}

func (v *NullableRequestPreservationTypes) Set(val *RequestPreservationTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestPreservationTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestPreservationTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestPreservationTypes(val *RequestPreservationTypes) *NullableRequestPreservationTypes {
	return &NullableRequestPreservationTypes{value: val, isSet: true}
}

func (v NullableRequestPreservationTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestPreservationTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


