/*
Administrative API Documentation

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API.

API version: 7.3.0.2-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the IdentityMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityMapping{}

// IdentityMapping An identity mapping.
type IdentityMapping struct {
	// (sortable) The identity mapping's class name.
	ClassName string `json:"className"`
	// When creating a new IdentityMapping, this is the ID for the IdentityMapping. If not specified, an ID will be automatically assigned. When updating an existing IdentityMapping, this field is ignored and the ID is determined by the path parameter.
	Id *int32 `json:"id,omitempty"`
	// (sortable) The name of the identity mapping.
	Name string `json:"name"`
	// The identity mapping's configuration data. - This value is a PingAccess plugin configuration (JSON).
	Configuration map[string]interface{} `json:"configuration,omitempty"`
}

// NewIdentityMapping instantiates a new IdentityMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityMapping(className string, name string) *IdentityMapping {
	this := IdentityMapping{}
	this.ClassName = className
	this.Name = name
	return &this
}

// NewIdentityMappingWithDefaults instantiates a new IdentityMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityMappingWithDefaults() *IdentityMapping {
	this := IdentityMapping{}
	return &this
}

// GetClassName returns the ClassName field value
func (o *IdentityMapping) GetClassName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassName
}

// GetClassNameOk returns a tuple with the ClassName field value
// and a boolean to check if the value has been set.
func (o *IdentityMapping) GetClassNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassName, true
}

// SetClassName sets field value
func (o *IdentityMapping) SetClassName(v string) {
	o.ClassName = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IdentityMapping) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityMapping) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IdentityMapping) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *IdentityMapping) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *IdentityMapping) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IdentityMapping) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IdentityMapping) SetName(v string) {
	o.Name = v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *IdentityMapping) GetConfiguration() map[string]interface{} {
	if o == nil || IsNil(o.Configuration) {
		var ret map[string]interface{}
		return ret
	}
	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityMapping) GetConfigurationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Configuration) {
		return map[string]interface{}{}, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *IdentityMapping) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given map[string]interface{} and assigns it to the Configuration field.
func (o *IdentityMapping) SetConfiguration(v map[string]interface{}) {
	o.Configuration = v
}

func (o IdentityMapping) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["className"] = o.ClassName
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	return toSerialize, nil
}

type NullableIdentityMapping struct {
	value *IdentityMapping
	isSet bool
}

func (v NullableIdentityMapping) Get() *IdentityMapping {
	return v.value
}

func (v *NullableIdentityMapping) Set(val *IdentityMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityMapping(val *IdentityMapping) *NullableIdentityMapping {
	return &NullableIdentityMapping{value: val, isSet: true}
}

func (v NullableIdentityMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
