/*
PingAccess Administrative API

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess.

API version: 7.1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SigningAlgorithms struct for SigningAlgorithms
type SigningAlgorithms struct {
	Items []Algorithm `json:"items"`
}

// NewSigningAlgorithms instantiates a new SigningAlgorithms object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSigningAlgorithms(items []Algorithm) *SigningAlgorithms {
	this := SigningAlgorithms{}
	this.Items = items
	return &this
}

// NewSigningAlgorithmsWithDefaults instantiates a new SigningAlgorithms object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSigningAlgorithmsWithDefaults() *SigningAlgorithms {
	this := SigningAlgorithms{}
	return &this
}

// GetItems returns the Items field value
func (o *SigningAlgorithms) GetItems() []Algorithm {
	if o == nil {
		var ret []Algorithm
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SigningAlgorithms) GetItemsOk() ([]Algorithm, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SigningAlgorithms) SetItems(v []Algorithm) {
	o.Items = v
}

func (o SigningAlgorithms) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableSigningAlgorithms struct {
	value *SigningAlgorithms
	isSet bool
}

func (v NullableSigningAlgorithms) Get() *SigningAlgorithms {
	return v.value
}

func (v *NullableSigningAlgorithms) Set(val *SigningAlgorithms) {
	v.value = val
	v.isSet = true
}

func (v NullableSigningAlgorithms) IsSet() bool {
	return v.isSet
}

func (v *NullableSigningAlgorithms) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSigningAlgorithms(val *SigningAlgorithms) *NullableSigningAlgorithms {
	return &NullableSigningAlgorithms{value: val, isSet: true}
}

func (v NullableSigningAlgorithms) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSigningAlgorithms) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


