/*
Administrative API Documentation

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API.

API version: 7.3.0.2-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the SiteAuthenticators type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteAuthenticators{}

// SiteAuthenticators A collection of site authenticators.
type SiteAuthenticators struct {
	// The actual list of site authenticators.
	Items []SiteAuthenticator `json:"items"`
}

// NewSiteAuthenticators instantiates a new SiteAuthenticators object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteAuthenticators(items []SiteAuthenticator) *SiteAuthenticators {
	this := SiteAuthenticators{}
	this.Items = items
	return &this
}

// NewSiteAuthenticatorsWithDefaults instantiates a new SiteAuthenticators object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteAuthenticatorsWithDefaults() *SiteAuthenticators {
	this := SiteAuthenticators{}
	return &this
}

// GetItems returns the Items field value
func (o *SiteAuthenticators) GetItems() []SiteAuthenticator {
	if o == nil {
		var ret []SiteAuthenticator
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SiteAuthenticators) GetItemsOk() ([]SiteAuthenticator, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SiteAuthenticators) SetItems(v []SiteAuthenticator) {
	o.Items = v
}

func (o SiteAuthenticators) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteAuthenticators) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableSiteAuthenticators struct {
	value *SiteAuthenticators
	isSet bool
}

func (v NullableSiteAuthenticators) Get() *SiteAuthenticators {
	return v.value
}

func (v *NullableSiteAuthenticators) Set(val *SiteAuthenticators) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteAuthenticators) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteAuthenticators) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteAuthenticators(val *SiteAuthenticators) *NullableSiteAuthenticators {
	return &NullableSiteAuthenticators{value: val, isSet: true}
}

func (v NullableSiteAuthenticators) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteAuthenticators) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
