/*
PingAccess Administrative API

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess.

API version: 7.1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ReplicaAdmins struct for ReplicaAdmins
type ReplicaAdmins struct {
	Items []ReplicaAdmin `json:"items"`
}

// NewReplicaAdmins instantiates a new ReplicaAdmins object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplicaAdmins(items []ReplicaAdmin) *ReplicaAdmins {
	this := ReplicaAdmins{}
	this.Items = items
	return &this
}

// NewReplicaAdminsWithDefaults instantiates a new ReplicaAdmins object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplicaAdminsWithDefaults() *ReplicaAdmins {
	this := ReplicaAdmins{}
	return &this
}

// GetItems returns the Items field value
func (o *ReplicaAdmins) GetItems() []ReplicaAdmin {
	if o == nil {
		var ret []ReplicaAdmin
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ReplicaAdmins) GetItemsOk() ([]ReplicaAdmin, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ReplicaAdmins) SetItems(v []ReplicaAdmin) {
	o.Items = v
}

func (o ReplicaAdmins) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableReplicaAdmins struct {
	value *ReplicaAdmins
	isSet bool
}

func (v NullableReplicaAdmins) Get() *ReplicaAdmins {
	return v.value
}

func (v *NullableReplicaAdmins) Set(val *ReplicaAdmins) {
	v.value = val
	v.isSet = true
}

func (v NullableReplicaAdmins) IsSet() bool {
	return v.isSet
}

func (v *NullableReplicaAdmins) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplicaAdmins(val *ReplicaAdmins) *NullableReplicaAdmins {
	return &NullableReplicaAdmins{value: val, isSet: true}
}

func (v NullableReplicaAdmins) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplicaAdmins) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


