/*
PingAccess Administrative API

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess.

API version: 7.1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Sites A collection of sites items.
type Sites struct {
	// The actual list of sites.
	Items []Site `json:"items"`
}

// NewSites instantiates a new Sites object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSites(items []Site) *Sites {
	this := Sites{}
	this.Items = items
	return &this
}

// NewSitesWithDefaults instantiates a new Sites object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSitesWithDefaults() *Sites {
	this := Sites{}
	return &this
}

// GetItems returns the Items field value
func (o *Sites) GetItems() []Site {
	if o == nil {
		var ret []Site
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *Sites) GetItemsOk() ([]Site, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *Sites) SetItems(v []Site) {
	o.Items = v
}

func (o Sites) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableSites struct {
	value *Sites
	isSet bool
}

func (v NullableSites) Get() *Sites {
	return v.value
}

func (v *NullableSites) Set(val *Sites) {
	v.value = val
	v.isSet = true
}

func (v NullableSites) IsSet() bool {
	return v.isSet
}

func (v *NullableSites) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSites(val *Sites) *NullableSites {
	return &NullableSites{value: val, isSet: true}
}

func (v NullableSites) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSites) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


