/*
Administrative API Documentation

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API.

API version: 7.3.0.2-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configurationapi

import (
	"encoding/json"
)

// checks if the AccessTokenValidators type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessTokenValidators{}

// AccessTokenValidators A collection of access token validators.
type AccessTokenValidators struct {
	// The actual list of access token validators.
	Items []AccessTokenValidator `json:"items"`
}

// NewAccessTokenValidators instantiates a new AccessTokenValidators object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessTokenValidators(items []AccessTokenValidator) *AccessTokenValidators {
	this := AccessTokenValidators{}
	this.Items = items
	return &this
}

// NewAccessTokenValidatorsWithDefaults instantiates a new AccessTokenValidators object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessTokenValidatorsWithDefaults() *AccessTokenValidators {
	this := AccessTokenValidators{}
	return &this
}

// GetItems returns the Items field value
func (o *AccessTokenValidators) GetItems() []AccessTokenValidator {
	if o == nil {
		var ret []AccessTokenValidator
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AccessTokenValidators) GetItemsOk() ([]AccessTokenValidator, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AccessTokenValidators) SetItems(v []AccessTokenValidator) {
	o.Items = v
}

func (o AccessTokenValidators) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessTokenValidators) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableAccessTokenValidators struct {
	value *AccessTokenValidators
	isSet bool
}

func (v NullableAccessTokenValidators) Get() *AccessTokenValidators {
	return v.value
}

func (v *NullableAccessTokenValidators) Set(val *AccessTokenValidators) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessTokenValidators) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessTokenValidators) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessTokenValidators(val *AccessTokenValidators) *NullableAccessTokenValidators {
	return &NullableAccessTokenValidators{value: val, isSet: true}
}

func (v NullableAccessTokenValidators) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessTokenValidators) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
