/*
PingAccess Administrative API

The PingAccess Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingAccess.

API version: 7.1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IdentityMappings A collection of identity mappings.
type IdentityMappings struct {
	// The actual list of identity mappings.
	Items []IdentityMapping `json:"items"`
}

// NewIdentityMappings instantiates a new IdentityMappings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityMappings(items []IdentityMapping) *IdentityMappings {
	this := IdentityMappings{}
	this.Items = items
	return &this
}

// NewIdentityMappingsWithDefaults instantiates a new IdentityMappings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityMappingsWithDefaults() *IdentityMappings {
	this := IdentityMappings{}
	return &this
}

// GetItems returns the Items field value
func (o *IdentityMappings) GetItems() []IdentityMapping {
	if o == nil {
		var ret []IdentityMapping
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *IdentityMappings) GetItemsOk() ([]IdentityMapping, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *IdentityMappings) SetItems(v []IdentityMapping) {
	o.Items = v
}

func (o IdentityMappings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableIdentityMappings struct {
	value *IdentityMappings
	isSet bool
}

func (v NullableIdentityMappings) Get() *IdentityMappings {
	return v.value
}

func (v *NullableIdentityMappings) Set(val *IdentityMappings) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityMappings) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityMappings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityMappings(val *IdentityMappings) *NullableIdentityMappings {
	return &NullableIdentityMappings{value: val, isSet: true}
}

func (v NullableIdentityMappings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityMappings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


